version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: shieldauth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: Authapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ahmed123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./drizzle:/docker-entrypoint-initdb.d
      - ./backup:/backup
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Authapp"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shieldauth_network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: shieldauth_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@authapp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shieldauth_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  shieldauth_network:
    driver: bridge
